In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
demand_set=pd.read_csv('Demand_History.csv')

In [3]:
demand_set

,demand_point_index,x_coordinate,y_coordinate,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,0,0.5,0.5,0.352242,0.667932,0.958593,2.911901,4.338274,6.561995,8.454417,10.595324,13.119572
1,1,1.5,0.5,0.325940,0.591964,0.862652,2.589068,4.196034,5.745551,8.753195,11.126995,12.020091
2,2,2.5,0.5,0.373752,0.591890,0.969733,2.641432,3.541772,5.469161,8.414627,10.115336,14.018254
3,3,3.5,0.5,0.420686,0.584055,0.906547,2.378577,3.888121,5.846089,9.083868,12.424885,15.012302
4,4,4.5,0.5,0.475621,0.647940,0.981544,2.665400,4.218711,6.776609,8.851107,11.731131,16.355563
...,...,...,...,...,...,...,...,...,...,...,...,...
4091,4091,59.5,63.5,0.171015,0.334565,0.556055,1.373291,1.837586,2.517146,3.352280,4.149888,5.426193
4092,4092,60.5,63.5,0.041716,0.061741,0.131291,0.386540,0.755846,0.941116,1.107797,1.309479,2.057450
4093,4093,61.5,63.5,0.100895,0.180352,0.296299,0.705373,1.300220,1.608609,1.822806,2.333681,3.218519
4094,4094,62.5,63.5,0.155353,0.290825,0.557803,1.516066,2.399426,2.719197,4.494515,6.096858,6.262574
4095,4095,63.5,63.5,0.209372,0.340185,0.749491,1.904285,2.775772,3.404641,4.574922,6.301078,6.860939

In [4]:
x = np.array([[2010],[2011],[2012],[2013],[2014],[2015],[2016],[2017]])

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly_reg3=PolynomialFeatures(degree=3)
x_poly_3=poly_reg3.fit_transform(x)

In [ ]:
x_poly_3

In [ ]:
ncol1=[]
for i in range(4096):
    y = demand_set.iloc[i,3:-1].values
    lin_reg_3=LinearRegression()
    lin_reg_3.fit(x_poly_3,y)
    ans1=lin_reg_3.predict(poly_reg3.transform([[2018]]))
    ncol1.append(ans1[0])

In [ ]:
demand_set['2018p']=ncol1

In [5]:
demand_set

,demand_point_index,x_coordinate,y_coordinate,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,0,0.5,0.5,0.352242,0.667932,0.958593,2.911901,4.338274,6.561995,8.454417,10.595324,13.119572
1,1,1.5,0.5,0.325940,0.591964,0.862652,2.589068,4.196034,5.745551,8.753195,11.126995,12.020091
2,2,2.5,0.5,0.373752,0.591890,0.969733,2.641432,3.541772,5.469161,8.414627,10.115336,14.018254
3,3,3.5,0.5,0.420686,0.584055,0.906547,2.378577,3.888121,5.846089,9.083868,12.424885,15.012302
4,4,4.5,0.5,0.475621,0.647940,0.981544,2.665400,4.218711,6.776609,8.851107,11.731131,16.355563
...,...,...,...,...,...,...,...,...,...,...,...,...
4091,4091,59.5,63.5,0.171015,0.334565,0.556055,1.373291,1.837586,2.517146,3.352280,4.149888,5.426193
4092,4092,60.5,63.5,0.041716,0.061741,0.131291,0.386540,0.755846,0.941116,1.107797,1.309479,2.057450
4093,4093,61.5,63.5,0.100895,0.180352,0.296299,0.705373,1.300220,1.608609,1.822806,2.333681,3.218519
4094,4094,62.5,63.5,0.155353,0.290825,0.557803,1.516066,2.399426,2.719197,4.494515,6.096858,6.262574
4095,4095,63.5,63.5,0.209372,0.340185,0.749491,1.904285,2.775772,3.404641,4.574922,6.301078,6.860939

In [ ]:
from sklearn.metrics import mean_squared_error
np.sqrt(mean_squared_error(demand_set['2018'],demand_set['2018p']))

In [ ]:
from sklearn.metrics import r2_score
r2_score(demand_set['2018'],demand_set['2018p'])

In [8]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
models=[['Decision Tree:',DecisionTreeRegressor()],['SVM:',SVR()],['Random Forest:',RandomForestRegressor()]]

for name,model in models:
    model=model
    ncol1=[]
    for i in range(4096):
        y = demand_set.iloc[i,3:-1].values
        model.fit(x,y)
        ans1=model.predict([[2018]])
        ncol1.append(ans1[0])
    print(name,(np.sqrt(mean_squared_error(demand_set['2018'],ncol1))))
    print(name,(r2_score(demand_set['2018'],ncol1)))

Decision Tree: 19.374119517388912
Decision Tree: 0.9406167371130175
SVM: 82.45700340325887
SVM: -0.07566045690765733
Random Forest: 26.374625077597525
Random Forest: 0.8899493284198258

In [ ]:
demand_set['2018']

In [ ]:
ncol1

In [ ]:
x

In [ ]:
y = demand_set.iloc[0,3:-2].values
y