In [1]:
import random
n = 10
m = 5
set_I = range(1, n+1)
set_J = range(1, m+1)
c = {(i,j): random.normalvariate(0,1) for i in set_I for j in set_J}
a = {(i,j): random.normalvariate(0,5) for i in set_I for j in set_J}
l = {(i,j): random.randint(0,10) for i in set_I for j in set_J}
u = {(i,j): random.randint(10,20) for i in set_I for j in set_J}
b = {j: random.randint(0,30) for j in set_J}

In [14]:
a

{(1, 1): -1.0292589125120504,
 (1, 2): -1.8191936267447564,
 (1, 3): 2.6060604167236017,
 (1, 4): -1.4741033999871964,
 (1, 5): 2.007293397610049,
 (2, 1): 2.2046600691013527,
 (2, 2): -1.6589998448330072,
 (2, 3): 2.6669017842958875,
 (2, 4): -4.656687579806743,
 (2, 5): -2.353252621992079,
 (3, 1): 6.75960692130748,
 (3, 2): 0.309068252112708,
 (3, 3): -6.230051365952685,
 (3, 4): 2.7027612696409813,
 (3, 5): 4.507688553563299,
 (4, 1): -4.651929551584962,
 (4, 2): 4.5829620788363385,
 (4, 3): -9.115787337051284,
 (4, 4): -7.76784878343434,
 (4, 5): 2.5730213677294533,
 (5, 1): -1.8069489121173985,
 (5, 2): 5.7751761844431595,
 (5, 3): -3.07998176002825,
 (5, 4): 1.2642926629451567,
 (5, 5): 4.389688313835517,
 (6, 1): 3.1774013797058447,
 (6, 2): 5.466161187207747,
 (6, 3): -1.9366381788638096,
 (6, 4): -3.997954914214353,
 (6, 5): 3.7871081568690146,
 (7, 1): -4.3616176555933475,
 (7, 2): 2.012509605888764,
 (7, 3): 2.5958682126497874,
 (7, 4): -0.5926207541274193,
 (7, 5): 0.9310218198107876,
 (8, 1): -0.8589290057660144,
 (8, 2): -10.13307314525248,
 (8, 3): -3.5015331537574648,
 (8, 4): 6.705954971115427,
 (8, 5): -7.679492523710698,
 (9, 1): 6.6799228796090295,
 (9, 2): 8.406741420341534,
 (9, 3): -1.380459956711977,
 (9, 4): 6.678646338687317,
 (9, 5): 5.84044784247107,
 (10, 1): -1.6376578547216705,
 (10, 2): -11.361083910938486,
 (10, 3): 1.2656224289261497,
 (10, 4): 5.187427140048031,
 (10, 5): -0.03841953164719867}

In [15]:
b

{1: 7, 2: 10, 3: 16, 4: 13, 5: 14}

In [16]:
l

{(1, 1): 0,
 (1, 2): 7,
 (1, 3): 2,
 (1, 4): 6,
 (1, 5): 3,
 (2, 1): 10,
 (2, 2): 4,
 (2, 3): 10,
 (2, 4): 6,
 (2, 5): 8,
 (3, 1): 1,
 (3, 2): 8,
 (3, 3): 2,
 (3, 4): 3,
 (3, 5): 2,
 (4, 1): 3,
 (4, 2): 3,
 (4, 3): 9,
 (4, 4): 3,
 (4, 5): 6,
 (5, 1): 0,
 (5, 2): 9,
 (5, 3): 10,
 (5, 4): 2,
 (5, 5): 5,
 (6, 1): 7,
 (6, 2): 3,
 (6, 3): 8,
 (6, 4): 9,
 (6, 5): 10,
 (7, 1): 9,
 (7, 2): 1,
 (7, 3): 5,
 (7, 4): 9,
 (7, 5): 0,
 (8, 1): 10,
 (8, 2): 9,
 (8, 3): 3,
 (8, 4): 10,
 (8, 5): 5,
 (9, 1): 7,
 (9, 2): 7,
 (9, 3): 0,
 (9, 4): 7,
 (9, 5): 2,
 (10, 1): 9,
 (10, 2): 9,
 (10, 3): 3,
 (10, 4): 7,
 (10, 5): 5}

In [17]:
u

{(1, 1): 12,
 (1, 2): 15,
 (1, 3): 10,
 (1, 4): 13,
 (1, 5): 13,
 (2, 1): 19,
 (2, 2): 16,
 (2, 3): 12,
 (2, 4): 11,
 (2, 5): 17,
 (3, 1): 15,
 (3, 2): 11,
 (3, 3): 12,
 (3, 4): 16,
 (3, 5): 11,
 (4, 1): 11,
 (4, 2): 14,
 (4, 3): 15,
 (4, 4): 17,
 (4, 5): 11,
 (5, 1): 14,
 (5, 2): 19,
 (5, 3): 18,
 (5, 4): 20,
 (5, 5): 17,
 (6, 1): 14,
 (6, 2): 11,
 (6, 3): 19,
 (6, 4): 13,
 (6, 5): 15,
 (7, 1): 15,
 (7, 2): 18,
 (7, 3): 14,
 (7, 4): 15,
 (7, 5): 18,
 (8, 1): 12,
 (8, 2): 12,
 (8, 3): 18,
 (8, 4): 15,
 (8, 5): 12,
 (9, 1): 14,
 (9, 2): 16,
 (9, 3): 14,
 (9, 4): 16,
 (9, 5): 18,
 (10, 1): 20,
 (10, 2): 12,
 (10, 3): 12,
 (10, 4): 19,
 (10, 5): 12}

In [19]:
c

{(1, 1): -0.2759486647070825,
 (1, 2): 0.42474495827294556,
 (1, 3): -1.7319423227290618,
 (1, 4): -0.07001211540636618,
 (1, 5): 0.016147544806858306,
 (2, 1): 0.2536242412818886,
 (2, 2): 0.8523538710357638,
 (2, 3): -0.9098887211857836,
 (2, 4): 0.41989068724668643,
 (2, 5): -0.12118674264116347,
 (3, 1): 0.9142477605670251,
 (3, 2): 0.5825814287461388,
 (3, 3): -1.7602123138491998,
 (3, 4): -0.3277030107836801,
 (3, 5): -1.26959780817866,
 (4, 1): 0.2808615362806067,
 (4, 2): -1.169515169801836,
 (4, 3): 1.4984198656931802,
 (4, 4): -1.0195610028561344,
 (4, 5): 0.3416730083728054,
 (5, 1): 0.8428027131289344,
 (5, 2): -0.5965806756338191,
 (5, 3): -1.3966999926907877,
 (5, 4): 2.9075438376010814,
 (5, 5): 0.6083906041893482,
 (6, 1): -0.6459299768701594,
 (6, 2): -0.8967921618008401,
 (6, 3): 1.808614869289334,
 (6, 4): 0.16388202711606176,
 (6, 5): -0.17260906257902012,
 (7, 1): 0.5675208355237547,
 (7, 2): 0.8098457910632234,
 (7, 3): -0.505373153331003,
 (7, 4): -1.5777761874087295,
 (7, 5): 0.009066353473608435,
 (8, 1): -0.4699328829175075,
 (8, 2): 2.007951078373095,
 (8, 3): 2.2124575722304467,
 (8, 4): -1.2016301027253298,
 (8, 5): -0.17977122342300403,
 (9, 1): 0.37830767436120255,
 (9, 2): 2.045014654335688,
 (9, 3): 0.13356568620727483,
 (9, 4): 0.4585274254915272,
 (9, 5): -0.6743060437374268,
 (10, 1): 0.977607596355305,
 (10, 2): -1.2937873958869295,
 (10, 3): -0.05425471745672797,
 (10, 4): 0.904762783046632,
 (10, 5): -0.9352065729975372}

In [21]:
set_I

range(1, 11)

In [22]:
set_J

range(1, 6)

In [2]:
import docplex.mp.model as cpx
opt_model = cpx.Model(name="MIP Model")

In [4]:
# if x is Continuous
x_vars  = {(i,j): opt_model.continuous_var(lb=l[i,j], ub= u[i,j],name="x_{0}_{1}".format(i,j)) 
for i in set_I for j in set_J}

In [5]:
# <= constraints
constraints = {j : 
opt_model.add_constraint(
ct=opt_model.sum(a[i,j] * x_vars[i,j] for i in set_I) <= b[j],
ctname="constraint_{0}".format(j))
    for j in set_J}

In [6]:
objective = opt_model.sum(x_vars[i,j] * c[i,j] 
                          for i in set_I 
                          for j in set_J)

In [7]:
# for minimization
opt_model.minimize(objective)

In [8]:
# solving with local cplex
opt_model.solve()

docplex.mp.solution.SolveSolution(obj=-121.742,values={x_1_1:12,x_1_2:7,..

In [10]:
import pandas as pd
opt_df = pd.DataFrame.from_dict(x_vars, orient="index",columns = ["variable_object"])
opt_df.index =pd.MultiIndex.from_tuples(opt_df.index,names=["column_i", "column_j"])
opt_df.reset_index(inplace=True)

In [12]:
# CPLEX
opt_df["solution_value"] =opt_df["variable_object"].apply(lambda item: item.solution_value)

In [13]:
opt_df

    column_i  column_j variable_object  solution_value
0          1         1           x_1_1       12.000000
1          1         2           x_1_2        7.000000
2          1         3           x_1_3       10.000000
3          1         4           x_1_4       13.000000
4          1         5           x_1_5        3.000000
5          2         1           x_2_1       10.000000
6          2         2           x_2_2        4.000000
7          2         3           x_2_3       12.000000
8          2         4           x_2_4        6.000000
9          2         5           x_2_5       17.000000
10         3         1           x_3_1        1.000000
11         3         2           x_3_2        8.000000
12         3         3           x_3_3       12.000000
13         3         4           x_3_4       16.000000
14         3         5           x_3_5       11.000000
15         4         1           x_4_1        7.824184
16         4         2           x_4_2       14.000000
17         4         3           x_4_3        9.000000
18         4         4           x_4_4       17.000000
19         4         5           x_4_5        6.000000
20         5         1           x_5_1        0.000000
21         5         2           x_5_2       11.996090
22         5         3           x_5_3       18.000000
23         5         4           x_5_4        2.000000
24         5         5           x_5_5        5.000000
25         6         1           x_6_1       14.000000
26         6         2           x_6_2       11.000000
27         6         3           x_6_3        8.000000
28         6         4           x_6_4        9.000000
29         6         5           x_6_5       10.000000
30         7         1           x_7_1        9.000000
31         7         2           x_7_2        1.000000
32         7         3           x_7_3       14.000000
33         7         4           x_7_4       15.000000
34         7         5           x_7_5        0.000000
35         8         1           x_8_1       12.000000
36         8         2           x_8_2        9.000000
37         8         3           x_8_3        3.000000
38         8         4           x_8_4       15.000000
39         8         5           x_8_5       12.000000
40         9         1           x_9_1        7.000000
41         9         2           x_9_2        7.000000
42         9         3           x_9_3        0.000000
43         9         4           x_9_4        7.000000
44         9         5           x_9_5        2.697761
45        10         1          x_10_1        9.000000
46        10         2          x_10_2       12.000000
47        10         3          x_10_3       12.000000
48        10         4          x_10_4        7.000000
49        10         5          x_10_5       12.000000