In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
n_supply=100
n_demand=4096
demand_set=pd.read_csv('Demand_History.csv')
supply_set=pd.read_csv('exisiting_EV_infrastructure_2018.csv')

In [3]:
mat=np.zeros((n_supply,n_demand))
for i in range (n_supply):
    for j in range(n_demand):
        d=demand_set.iloc[j,1:3].values
        s=supply_set.iloc[i,1:3].values
        ans=math.sqrt(np.square(s[0]-d[0])+np.square(s[1]-d[1]))
        mat[i][j]=ans
mat

array([[53.14215611, 52.20883581, 51.27802958, ..., 45.52225335,
        45.78153919, 46.06108022],
       [68.38785811, 67.8544489 , 67.33166666, ..., 24.75540075,
        25.73241079, 26.71112248],
       [73.39766971, 72.77224371, 72.15525616, ..., 15.95179219,
        16.88316352, 17.8219737 ],
       ...,
       [41.81242567, 40.96146071, 40.11737262, ..., 48.39291434,
        48.92276036, 49.46714873],
       [56.71278449, 55.96843837, 55.23216692, ..., 31.44214632,
        32.04270174, 32.66283673],
       [19.37856861, 18.39424899, 17.41171648, ..., 72.91708351,
        73.49639816, 74.08468139]])

In [4]:
dist_matrix=pd.DataFrame(mat)
dist_matrix

,0,1,2,3,4,5,6,7,8,9,...,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095
0,53.142156,52.208836,51.278030,50.349877,49.424527,48.502141,47.582890,46.666961,45.754552,44.845878,...,44.300780,44.409828,44.541067,44.694300,44.869301,45.065818,45.283571,45.522253,45.781539,46.061080
1,68.387858,67.854449,67.331667,66.819761,66.318983,65.829588,65.351830,64.885968,64.432258,63.990961,...,17.987223,18.943792,19.904632,20.869151,21.836863,22.807360,23.780302,24.755401,25.732411,26.711122
2,73.397670,72.772244,72.155256,71.546925,70.947474,70.357129,69.776122,69.204687,68.643064,68.091495,...,9.817786,10.628756,11.469612,12.334242,13.217983,14.117245,15.029243,15.951792,16.883164,17.821974
3,62.558091,62.084277,61.623049,61.174692,60.739490,60.317729,59.909692,59.515661,59.135917,58.770736,...,25.309363,26.258458,27.211199,28.167217,29.126188,30.087831,31.051898,32.018168,32.986449,33.956569
4,61.656645,60.831721,60.012122,59.198068,58.389791,57.587534,56.791553,56.002116,55.219502,54.444006,...,28.539067,28.660684,28.816510,29.005994,29.228481,29.483225,29.769397,30.086100,30.432382,30.807244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,49.423023,48.514871,47.610402,46.709827,45.813377,44.921299,44.033859,43.151342,42.274057,41.402337,...,43.449039,43.667798,43.908247,44.170032,44.452777,44.756083,45.079536,45.422705,45.785147,46.166409
96,44.393460,43.728052,43.075582,42.436646,41.811866,41.201885,40.607371,40.029012,39.467518,38.923620,...,38.619456,39.253351,39.902240,40.565404,41.242153,41.931830,42.633808,43.347489,44.072304,44.807714
97,41.812426,40.961461,40.117373,39.280605,38.451635,37.630979,36.819192,36.016874,35.224672,34.443284,...,45.132448,45.546682,45.978936,46.428707,46.895492,47.378788,47.878093,48.392914,48.922760,49.467149
98,56.712784,55.968438,55.232167,54.504297,53.785171,53.075143,52.374583,51.683877,51.003424,50.333641,...,27.887728,28.316983,28.774602,29.259253,29.769616,30.304393,30.862314,31.442146,32.042702,32.662837
99,19.378569,18.394249,17.411716,16.431292,15.453376,14.478477,13.507249,12.540544,11.579496,10.625638,...,69.131503,69.641828,70.162694,70.693869,71.235122,71.786225,72.346953,72.917084,73.496398,74.084681

dist_matrix.to_csv('Distance_Matrix.csv',index=False)